workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.abbas.appfactory"
    scripts:
      - name: Check project
        script: |
          set -e
          test -f settings.gradle
          test -d app
      - name: Build APK
        script: |
          set -e
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi
    artifacts:
      - app/build/outputs/apk/**/*.apk
