plugins {
    id 'com.android.application'
}

android {
    namespace 'com.abbas.appfactory'
    compileSdk 35

    defaultConfig {
        applicationId 'com.abbas.appfactory'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
